'''2) Armazene os valores 5, -5, 30 e 0 e escreva se é positivo ou negativo (considere o valor zero ou maiores que zero como positivo).'''

valor1 = 5
valor2 = -5
valor3 = 30
valor4 = 0

if valor1 >= 0:
    print('O valor:', valor1, 'é positivo!')
else:
    print('O valor:', valor1, 'é negativo!')
    
if valor2 >= 0:
    print('O valor:', valor2, 'é positivo!')
else:
    print('O valor:', valor2, 'é negativo!')
    
if valor1 >= 0:
    print('O valor:', valor3, 'é positivo!')
else:
    print('O valor:', valor3, 'é negativo!')
    
if valor1 >= 0:
    print('O valor:', valor4, 'é positivo!')
else:
    print('O valor:', valor4, 'é negativo!')
